# Generated by Django 5.1.7 on 2025-03-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(default=90, max_length=12)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parlour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Par_name', models.CharField(max_length=100)),
                ('Makeup_cat', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('img', models.URLField(default='https://w7.pngwing.com/pngs/370/703/png-transparent-makeup-cosmetics-makeup-cosmetics-lipstick-brush-thumbnail.png')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
