# Generated by Django 5.1.7 on 2025-03-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MakeupApp', '0002_menu_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='res',
            new_name='par',
        ),
    ]
